language: python
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv install
script: python manage.py test
deploy:
  provider: codedeploy
  revision_type: github
  application: DiaryApi
  deployment_group: DiaryApi_DepGrp
  region: eu-central-1
  file_exists_behavior: overwrite
  edge: true
