version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/diary_api/
hooks:
  AfterInstall:
    - location: scripts/create_enviroment
      timeout: 1000
  ApplicationStart:
    - location: scripts/start_server
      timeout: 1000
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 1000
      runas: root
